version: "3"
services:
  notebook:
    build: .
    ports:
      - 8888:8888
    volumes:
      - $PWD/work/:/home/jovyan/work/
    environment:
      - TZ=Asia/Tokyo
    command:
      - jupyter
      - notebook
      - --NotebookApp.iopub_data_rate_limit=10000000
